import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { getFirestore, collection, getDocs, doc, setDoc, updateDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || "AIzaSyBPw7Z_nhz7osMlGcdw4wAqXGFUkH27kug",
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || "nexa-index.firebaseapp.com",
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || "nexa-index",
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || "nexa-index.firebasestorage.app",
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "1089214920796",
  appId: process.env.VITE_FIREBASE_APP_ID || "1:1089214920796:web:120f3b158f599b0236ce99",
  measurementId: process.env.VITE_FIREBASE_MEASUREMENT_ID || "G-JB7DJRKXV4"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

// Lista completa dos 94 lançamentos de Taguatinga (69 Atrasados + 25 Pagos)
const taguatingaPayables = [
  // ==========================================
  // BLOCO 1: LANÇAMENTOS ATRASADOS (IMAGEM 1)
  // ==========================================
  {
    supplier: "JTD IMOVEIS LTDA",
    invoiceNumber: "146",
    installment: 1,
    dueDate: "2026-08-01",
    paymentDate: "",
    amount: 1200.25,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Aluguel Imóvel Taguatinga"
  },
  {
    supplier: "FARMARIN INDUSTRIA E COMERCIO LTDA",
    invoiceNumber: "446467",
    installment: "01/14",
    dueDate: "2026-08-02",
    paymentDate: "",
    amount: 17007.65,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Acordo / Insumos Farmarin Parc 01/14"
  },
  {
    supplier: "ADVOGADO FARMARIN",
    invoiceNumber: "PAR. 03/06",
    installment: "03/06",
    dueDate: "2026-08-02",
    paymentDate: "",
    amount: 2751.65,
    amountPaid: 0,
    status: "Atrasado",
    category: "Jurídico, Contabilidade & Taxas Regulatórias",
    costCenterId: "3.2",
    natureType: "Custo Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Honorários Advocatícios Farmarin Parc 03/06"
  },
  {
    supplier: "REMORA HOSPITALAR",
    invoiceNumber: "14080",
    installment: 2,
    dueDate: "2026-08-02",
    paymentDate: "",
    amount: 3061.35,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos Hospitalares Remora"
  },
  {
    supplier: "CONÁGUA SOLUÇÕES LTDA",
    invoiceNumber: "3857",
    installment: 1,
    dueDate: "2026-08-03",
    paymentDate: "",
    amount: 1978.65,
    amountPaid: 0,
    status: "Atrasado",
    category: "Tratamento de Água & Osmose Reversa",
    costCenterId: "2.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Soluções e Tratamento de Água / Osmose"
  },
  {
    supplier: "RM HOSPITALAR LTDA",
    invoiceNumber: "425587",
    installment: 2,
    dueDate: "2026-08-04",
    paymentDate: "",
    amount: 904.73,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Material Médico RM Hospitalar"
  },
  {
    supplier: "PRO RENAL BRASIL FUND.AMPARO A PESQ EM ENFERMIDADE",
    invoiceNumber: "1569",
    installment: 1,
    dueDate: "2026-08-05",
    paymentDate: "",
    amount: 830.84,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Fundação Pró Renal Brasil"
  },
  {
    supplier: "REMORA HOSPITALAR",
    invoiceNumber: "14333",
    installment: 1,
    dueDate: "2026-08-05",
    paymentDate: "",
    amount: 3053.70,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos Hospitalares Remora"
  },
  {
    supplier: "KORE LOGÍSTICA INTELIGENTE PARA SAÚDE LTDA",
    invoiceNumber: "3267",
    installment: 1,
    dueDate: "2026-08-06",
    paymentDate: "",
    amount: 7800.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Logística Inteligente em Saúde"
  },
  {
    supplier: "REEMBOLSO DALIA VIAGEM 21/07 A 25/07 DE 2026",
    invoiceNumber: "REEMBOLSO-DALIA-2125",
    installment: 1,
    dueDate: "2026-08-07",
    paymentDate: "",
    amount: 2226.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Custo Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Reembolso Deslocamento/Viagem Dra. Dalia"
  },
  {
    supplier: "COMERCIAL CIRURGICA RIOCLARENSE LTDA",
    invoiceNumber: "2179886",
    installment: 1,
    dueDate: "2026-08-07",
    paymentDate: "",
    amount: 3450.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Medicamentos & Farmácia Clínica",
    costCenterId: "1.2",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Medicamentos Cirúrgica Rioclarense"
  },
  {
    supplier: "PESO EMPREENDIMENTOS",
    invoiceNumber: "45",
    installment: 1,
    dueDate: "2026-08-08",
    paymentDate: "",
    amount: 1853.30,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Locação / Empreendimentos"
  },
  {
    supplier: "LABORATORIOS B.BRAUN S.A.",
    invoiceNumber: "182587",
    installment: 1,
    dueDate: "2026-08-09",
    paymentDate: "",
    amount: 1128.48,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Soluções B.Braun"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526357324",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 244.50,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355624",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 218.44,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355114",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 211.70,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526354814",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 215.73,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "FUSÃO PAPELARIA E LIVRARIA EIRELIES",
    invoiceNumber: "6543",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 635.61,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Material de Escritório / Papelaria"
  },
  {
    supplier: "CONDOMÍNIO PRIME EXCELENCIA MÉDICA LTDA",
    invoiceNumber: "13840950",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 14019.32,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Taxa Condominial Prime Excelência Médica"
  },
  {
    supplier: "MEDICAR EMERGENCIAS MÉDICAS LTDA",
    invoiceNumber: "403568",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 658.35,
    amountPaid: 0,
    status: "Atrasado",
    category: "Serviços Médicos & Honorários PJ",
    costCenterId: "1.8",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Cobertura de Emergências Médicas"
  },
  {
    supplier: "JONATHA DE JESUS SILVA",
    invoiceNumber: "82",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 200.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Serviços Médicos & Honorários PJ",
    costCenterId: "1.8",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Serviços Prestados Jonatha"
  },
  {
    supplier: "KLEYSON FERNANDO SARAIVA",
    invoiceNumber: "252",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 650.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Custo Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Serviços Administrativos Kleyson"
  },
  {
    supplier: "TECNOPONTO TECNOLOGIA AVANÇADA CONTROLE DE PONTO",
    invoiceNumber: "138887",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 320.56,
    amountPaid: 0,
    status: "Atrasado",
    category: "TI, Telecom & Softwares de Saúde",
    costCenterId: "2.4",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Sistema / Software de Ponto Eletrônico"
  },
  {
    supplier: "YOMA COMERCIO DE ALIMENTOS EIRELI",
    invoiceNumber: "1256",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 2009.70,
    amountPaid: 0,
    status: "Atrasado",
    category: "Nutrição, Dietética & Copa de Pacientes",
    costCenterId: "2.6",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Alimentos e Lanches de Pacientes em Diálise"
  },
  {
    supplier: "BSB DISTRIBUIDORA DE PRODUTOS HOSPITALARES LTDA",
    invoiceNumber: "13911",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "",
    amount: 342.48,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos Hospitalares BSB"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355544",
    installment: 1,
    dueDate: "2026-08-11",
    paymentDate: "",
    amount: 215.83,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355034",
    installment: 1,
    dueDate: "2026-08-11",
    paymentDate: "",
    amount: 211.70,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526354734",
    installment: 1,
    dueDate: "2026-08-11",
    paymentDate: "",
    amount: 203.82,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "ARTHUR VINICIUS FERREIRA GONCALVES",
    invoiceNumber: "44",
    installment: 1,
    dueDate: "2026-08-11",
    paymentDate: "",
    amount: 6867.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Custo Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Carreto e Transporte Taguatinga NF 44"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526357164",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "",
    amount: 223.41,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355464",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "",
    amount: 264.69,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526354654",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "",
    amount: 236.55,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "LABORATORIOS B.BRAUN S.A.",
    invoiceNumber: "33909",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "",
    amount: 9900.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Soluções B.Braun"
  },
  {
    supplier: "LABORATORIOS B.BRAUN S.A.",
    invoiceNumber: "33910",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "",
    amount: 1905.30,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Soluções B.Braun"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355384",
    installment: 1,
    dueDate: "2026-08-13",
    paymentDate: "",
    amount: 257.18,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526354574",
    installment: 1,
    dueDate: "2026-08-13",
    paymentDate: "",
    amount: 244.50,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "LABORATORIOS B.BRAUN S.A.",
    invoiceNumber: "33957",
    installment: 1,
    dueDate: "2026-08-13",
    paymentDate: "",
    amount: 1416.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Soluções B.Braun"
  },
  {
    supplier: "COMERCIAL CIRURGICA RIOCLARENSE LTDA",
    invoiceNumber: "2180787",
    installment: 1,
    dueDate: "2026-08-13",
    paymentDate: "",
    amount: 12025.56,
    amountPaid: 0,
    status: "Atrasado",
    category: "Medicamentos & Farmácia Clínica",
    costCenterId: "1.2",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Medicamentos Cirúrgica Rioclarense"
  },
  {
    supplier: "CARRETO TAGUATINGA ARTHUR VINICIUS",
    invoiceNumber: "44-B",
    installment: 1,
    dueDate: "2026-08-13",
    paymentDate: "",
    amount: 6867.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Custo Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Carreto e Transporte Taguatinga NF 44"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526354494",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 217.50,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355704",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 223.41,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526355244",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 210.83,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "PRIME CONSTRUÇÃO E INCORPORAÇÃO S/A",
    invoiceNumber: "526354944",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 215.56,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Condomínio / Salas Prime Incorporação"
  },
  {
    supplier: "LABORATORIOS B.BRAUN S.A.",
    invoiceNumber: "33288",
    installment: 2,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 2040.61,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Soluções B.Braun"
  },
  {
    supplier: "LABORATORIOS B.BRAUN S.A.",
    invoiceNumber: "178996",
    installment: 2,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 1080.20,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Soluções B.Braun"
  },
  {
    supplier: "LF WOLF ARIAS HOSPITALARES LTDA",
    invoiceNumber: "29053",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 532.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos Médicos Wolf Arias"
  },
  {
    supplier: "NIPRO MEDICAL CORPORATION PRODUTOS MÉDICOS LTDA",
    invoiceNumber: "190235",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "",
    amount: 2122.50,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Dialisadores Nipro Medical"
  },
  {
    supplier: "RIMTEC MANUTENÇÃO DE EQUIPAMENTOS",
    invoiceNumber: "8002",
    installment: 1,
    dueDate: "2026-08-16",
    paymentDate: "",
    amount: 108.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Engenharia Clínica & Manutenção de Equipamentos",
    costCenterId: "2.2",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Manutenção Preventiva / Corretiva Rimtec"
  },
  {
    supplier: "CONSELHO REGIONAL DE MEDICINA-MG",
    invoiceNumber: "CRM-PARC-5",
    installment: 5,
    dueDate: "2026-08-17",
    paymentDate: "",
    amount: 1189.08,
    amountPaid: 0,
    status: "Atrasado",
    category: "Jurídico, Contabilidade & Taxas Regulatórias",
    costCenterId: "3.2",
    natureType: "Custo Operacional",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Anuidade / Taxa CRM Parcela 5"
  },
  {
    supplier: "CONSELHO REGIONAL DE MEDICINA - CRM",
    invoiceNumber: "186605907",
    installment: 1,
    dueDate: "2026-08-17",
    paymentDate: "",
    amount: 1189.08,
    amountPaid: 0,
    status: "Atrasado",
    category: "Jurídico, Contabilidade & Taxas Regulatórias",
    costCenterId: "3.2",
    natureType: "Custo Operacional",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Anuidade / Taxa CRM Doc 186605907"
  },
  {
    supplier: "SISTEMED BRASÍLIA CALIBRAÇÃO EQUIP.HOSP. LTDA",
    invoiceNumber: "1221",
    installment: 1,
    dueDate: "2026-08-17",
    paymentDate: "",
    amount: 400.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Engenharia Clínica & Manutenção de Equipamentos",
    costCenterId: "2.2",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Calibração de Equipamentos Hospitalares"
  },
  {
    supplier: "FRESENIUS MEDICAL CARE - ALUGUEL DE MÁQUINAS",
    invoiceNumber: "7",
    installment: "ref 7/26",
    dueDate: "2026-08-19",
    paymentDate: "",
    amount: 61796.40,
    amountPaid: 0,
    status: "Atrasado",
    category: "Engenharia Clínica & Manutenção de Equipamentos",
    costCenterId: "2.2",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Locação de Máquinas de Hemodiálise Fresenius Ref 07/2026"
  },
  {
    supplier: "GUIA FGTS",
    invoiceNumber: "FGTS-082026",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 6833.81,
    amountPaid: 0,
    status: "Atrasado",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Guia FGTS Geral Competência 07/2026"
  },
  {
    supplier: "GUIA FGTS CONSIGNADO",
    invoiceNumber: "FGTS-CONS-082026",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 4635.30,
    amountPaid: 0,
    status: "Atrasado",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Guia FGTS Consignado Competência 07/2026"
  },
  {
    supplier: "GUIA DCTFWEB",
    invoiceNumber: "INSS-DCTFWEB-082026",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 38904.31,
    amountPaid: 0,
    status: "Atrasado",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Guia DCTFWeb / INSS Competência 07/2026"
  },
  {
    supplier: "YOMA COMERCIO DE ALIMENTOS EIRELI",
    invoiceNumber: "1251",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 423.40,
    amountPaid: 0,
    status: "Atrasado",
    category: "Nutrição, Dietética & Copa de Pacientes",
    costCenterId: "2.6",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Alimentos e Lanches de Pacientes em Diálise"
  },
  {
    supplier: "NEOENERGIA BRASÍLIA",
    invoiceNumber: "12345",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 55.29,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Conta de Energia Elétrica Taguatinga"
  },
  {
    supplier: "NEOENERGIA BRASÍLIA",
    invoiceNumber: "123456",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 56.12,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Conta de Energia Elétrica Taguatinga"
  },
  {
    supplier: "TECNOLTA EQUIPAMENTOS ELETRONICOS LTDA",
    invoiceNumber: "4129",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 735.96,
    amountPaid: 0,
    status: "Atrasado",
    category: "TI, Telecom & Softwares de Saúde",
    costCenterId: "2.4",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Equipamentos Eletrônicos / TI"
  },
  {
    supplier: "CONÁGUA SOLUÇÕES LTDA",
    invoiceNumber: "4026",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 1279.95,
    amountPaid: 0,
    status: "Atrasado",
    category: "Tratamento de Água & Osmose Reversa",
    costCenterId: "2.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Soluções e Tratamento de Água / Osmose"
  },
  {
    supplier: "YOMA COMERCIO DE ALIMENTOS EIRELI",
    invoiceNumber: "1245",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 3897.50,
    amountPaid: 0,
    status: "Atrasado",
    category: "Nutrição, Dietética & Copa de Pacientes",
    costCenterId: "2.6",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Alimentos e Lanches de Pacientes em Diálise"
  },
  {
    supplier: "PONTUAL DF ENTREGAS LTDA",
    invoiceNumber: "263",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 40.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Custo Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Entregas Rápidas e Motoboy DF"
  },
  {
    supplier: "YOMA COMERCIO DE ALIMENTOS EIRELI",
    invoiceNumber: "1248",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "",
    amount: 868.58,
    amountPaid: 0,
    status: "Atrasado",
    category: "Nutrição, Dietética & Copa de Pacientes",
    costCenterId: "2.6",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Alimentos e Lanches de Pacientes em Diálise"
  },
  {
    supplier: "EMPRESTIMO BANCARIO",
    invoiceNumber: "644707",
    installment: 23,
    dueDate: "2026-08-22",
    paymentDate: "",
    amount: 9040.09,
    amountPaid: 0,
    status: "Atrasado",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Amortização Financeira",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Amortização Empréstimo Bancário Parc 23 Contrato 644707"
  },
  {
    supplier: "CAESB - ÁGUA E ESGOTO DE BRASÍLIA",
    invoiceNumber: "AGUA-082026",
    installment: 1,
    dueDate: "2026-08-22",
    paymentDate: "",
    amount: 22414.54,
    amountPaid: 0,
    status: "Atrasado",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Conta de Água e Esgoto Taguatinga"
  },
  {
    supplier: "LMA COMERCIO E SERVICOS EIRELI LTDA",
    invoiceNumber: "33677",
    installment: 1,
    dueDate: "2026-08-23",
    paymentDate: "",
    amount: 3995.14,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Material Médico-Hospitalar LMA"
  },
  {
    supplier: "RIMTEC MANUTENÇÃO DE EQUIPAMENTOS",
    invoiceNumber: "8099",
    installment: 1,
    dueDate: "2026-08-24",
    paymentDate: "",
    amount: 38.80,
    amountPaid: 0,
    status: "Atrasado",
    category: "Engenharia Clínica & Manutenção de Equipamentos",
    costCenterId: "2.2",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Manutenção Preventiva / Corretiva Rimtec"
  },
  {
    supplier: "RIMTEC MANUTENÇÃO DE EQUIPAMENTOS",
    invoiceNumber: "1342",
    installment: 1,
    dueDate: "2026-08-24",
    paymentDate: "",
    amount: 2700.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Engenharia Clínica & Manutenção de Equipamentos",
    costCenterId: "2.2",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Manutenção Preventiva / Corretiva Rimtec"
  },
  {
    supplier: "LABORATORIOS B.BRAUN S.A.",
    invoiceNumber: "33512",
    installment: 2,
    dueDate: "2026-08-24",
    paymentDate: "",
    amount: 3540.00,
    amountPaid: 0,
    status: "Atrasado",
    category: "Material Médico-Hospitalar (MatMed)",
    costCenterId: "1.1",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Insumos e Soluções B.Braun"
  },

  // ==========================================
  // BLOCO 2: LANÇAMENTOS PAGOS (IMAGEM 2)
  // ==========================================
  {
    supplier: "RIMTEC MANUTENÇÃO DE EQUIPAMENTOS",
    invoiceNumber: "7955",
    installment: 1,
    dueDate: "2026-08-01",
    paymentDate: "2026-08-05",
    amount: 140.00,
    amountPaid: 144.68,
    status: "Pago",
    category: "Engenharia Clínica & Manutenção de Equipamentos",
    costCenterId: "2.2",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Manutenção de Equipamentos Rimtec"
  },
  {
    supplier: "ABA IMÓVEIS LTDA",
    invoiceNumber: "509",
    installment: 1,
    dueDate: "2026-08-01",
    paymentDate: "2026-08-03",
    amount: 18120.61,
    amountPaid: 18120.61,
    status: "Pago",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Aluguel Imóvel Clínica Taguatinga Aba Imóveis"
  },
  {
    supplier: "NEOENERGIA BRASÍLIA",
    invoiceNumber: "4237323",
    installment: 1,
    dueDate: "2026-08-03",
    paymentDate: "2026-08-04",
    amount: 12788.64,
    amountPaid: 12788.64,
    status: "Pago",
    category: "Infraestrutura, Aluguel & Predial",
    costCenterId: "4.1",
    natureType: "Custo Fixo / Operacional",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Conta de Energia Elétrica Taguatinga"
  },
  {
    supplier: "EMPRESTIMO BANCARIO",
    invoiceNumber: "680870",
    installment: 19,
    dueDate: "2026-08-05",
    paymentDate: "2026-08-05",
    amount: 22516.53,
    amountPaid: 22516.53,
    status: "Pago",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Amortização Financeira",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Amortização Empréstimo Bancário Parc 19 Contrato 680870"
  },
  {
    supplier: "FOLHA DE PAGAMENTO CLT",
    invoiceNumber: "FOLHA-082026",
    installment: 1,
    dueDate: "2026-08-06",
    paymentDate: "2026-08-06",
    amount: 78784.08,
    amountPaid: 78784.08,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Folha de Pagamento Funcionários CLT Ref 07/2026"
  },
  {
    supplier: "RBC SERVIÇOS E ENGENHARIA AMBIENTAL LTDA",
    invoiceNumber: "9",
    installment: 1,
    dueDate: "2026-08-06",
    paymentDate: "2026-08-10",
    amount: 1300.00,
    amountPaid: 1300.00,
    status: "Pago",
    category: "Gestão de Resíduos de Saúde (Lixo Infectante/RSS)",
    costCenterId: "2.3",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Coleta e Destinação de Resíduos Infectantes (RSS)"
  },
  {
    supplier: "VA/VT REF 08-2026 FRANCINETE",
    invoiceNumber: "VAVT-FRANCINETE",
    installment: 1,
    dueDate: "2026-08-07",
    paymentDate: "2026-08-07",
    amount: 864.00,
    amountPaid: 864.00,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Vale Alimentação e Transporte Francinete Ref 08/2026"
  },
  {
    supplier: "PLANO TELEFONICO CLARO",
    invoiceNumber: "TEL-CLARO-TAG",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "2026-08-10",
    amount: 63.90,
    amountPaid: 63.90,
    status: "Pago",
    category: "TI, Telecom & Softwares de Saúde",
    costCenterId: "2.4",
    natureType: "Custo Operacional",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Telefonia Móvel / Corporativa Claro"
  },
  {
    supplier: "FLIT APP TECNOLOGIA",
    invoiceNumber: "27545",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "2026-08-04",
    amount: 410.90,
    amountPaid: 419.20,
    status: "Pago",
    category: "TI, Telecom & Softwares de Saúde",
    costCenterId: "2.4",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Software de Gestão Flit App Tecnologia"
  },
  {
    supplier: "CLARO S/A",
    invoiceNumber: "559362955",
    installment: 1,
    dueDate: "2026-08-10",
    paymentDate: "2026-08-04",
    amount: 199.80,
    amountPaid: 199.80,
    status: "Pago",
    category: "TI, Telecom & Softwares de Saúde",
    costCenterId: "2.4",
    natureType: "Custo Operacional",
    paymentMethod: "Boleto Bancário",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Internet Fibra e Telefonia Claro S/A"
  },
  {
    supplier: "DIFERENÇA SALARIAL RENATA",
    invoiceNumber: "DIF-SAL-RENATA",
    installment: 1,
    dueDate: "2026-08-11",
    paymentDate: "2026-08-11",
    amount: 689.10,
    amountPaid: 689.10,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Diferença Salarial Folha Renata"
  },
  {
    supplier: "TRCT CLEIDEMEIRE REIS",
    invoiceNumber: "TRCT-CLEIDEMEIRE",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "2026-08-12",
    amount: 0.00,
    amountPaid: 0.00,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Rescisão TRCT Cleidemeire Reis (Zerada)"
  },
  {
    supplier: "TRCT DANUBIA PEREIRA",
    invoiceNumber: "TRCT-DANUBIA",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "2026-08-12",
    amount: 2459.73,
    amountPaid: 2459.73,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Rescisão TRCT Danubia Pereira"
  },
  {
    supplier: "FGTS DANUBIA PEREIRA",
    invoiceNumber: "FGTS-DANUBIA-1",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "2026-08-12",
    amount: 299.91,
    amountPaid: 299.91,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Guia Rescisória FGTS Danubia Pereira"
  },
  {
    supplier: "FGTS DANUBIA PEREIRA",
    invoiceNumber: "FGTS-DANUBIA-2",
    installment: 1,
    dueDate: "2026-08-12",
    paymentDate: "2026-08-12",
    amount: 114.32,
    amountPaid: 114.32,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Guia Complementar FGTS Danubia Pereira"
  },
  {
    supplier: "TRCT TUANY APARECIDA",
    invoiceNumber: "TRCT-TUANY",
    installment: 1,
    dueDate: "2026-08-13",
    paymentDate: "2026-08-12",
    amount: 390.16,
    amountPaid: 390.16,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Rescisão TRCT Tuany Aparecida"
  },
  {
    supplier: "FGTS TUANY APARECIDA",
    invoiceNumber: "FGTS-TUANY",
    installment: 1,
    dueDate: "2026-08-13",
    paymentDate: "2026-08-12",
    amount: 2064.87,
    amountPaid: 2064.87,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Guia Rescisória FGTS Tuany Aparecida"
  },
  {
    supplier: "TRCT WALLISON FERREIRA",
    invoiceNumber: "TRCT-WALLISON",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "2026-08-14",
    amount: 2099.64,
    amountPaid: 2099.64,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Rescisão TRCT Wallison Ferreira"
  },
  {
    supplier: "FGTS WALLISON FERREIRA",
    invoiceNumber: "FGTS-WALLISON",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "2026-08-14",
    amount: 299.91,
    amountPaid: 299.91,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Guia / Boleto",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Guia Rescisória FGTS Wallison Ferreira"
  },
  {
    supplier: "VA/VT REF 08-2026 CAIO FEITOSA",
    invoiceNumber: "VAVT-CAIO",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "2026-08-19",
    amount: 725.40,
    amountPaid: 725.40,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Vale Alimentação e Transporte Caio Feitosa Ref 08/2026"
  },
  {
    supplier: "VA/VT REF 08-2026 ELEN DE CASTRO",
    invoiceNumber: "VAVT-ELEN",
    installment: 1,
    dueDate: "2026-08-14",
    paymentDate: "2026-08-14",
    amount: 661.50,
    amountPaid: 661.50,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Vale Alimentação e Transporte Elen de Castro Ref 08/2026"
  },
  {
    supplier: "TAGUATINGA ITAU",
    invoiceNumber: "ITAU-PARC-3-3",
    installment: "3-3",
    dueDate: "2026-08-18",
    paymentDate: "2026-08-07",
    amount: 6022.22,
    amountPaid: 5975.63,
    status: "Pago",
    category: "Despesas Gerais & Administrativas",
    costCenterId: "3.3",
    natureType: "Amortização Financeira",
    paymentMethod: "Débito em Conta",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Parcela Financiamento / Contrato Itaú 3-3"
  },
  {
    supplier: "VA/VT REF 08-2026 DIEGO R",
    invoiceNumber: "VAVT-DIEGO",
    installment: 1,
    dueDate: "2026-08-19",
    paymentDate: "2026-08-19",
    amount: 473.20,
    amountPaid: 473.20,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Vale Alimentação e Transporte Diego R Ref 08/2026"
  },
  {
    supplier: "VAVT REF 08-2026 ANA PAULA G",
    invoiceNumber: "VAVT-ANAPAULA",
    installment: 1,
    dueDate: "2026-08-19",
    paymentDate: "2026-08-19",
    amount: 443.30,
    amountPaid: 443.30,
    status: "Pago",
    category: "Folha de Pagamento & Encargos Sociais",
    costCenterId: "3.1",
    natureType: "Custo com Pessoal",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Vale Alimentação e Transporte Ana Paula G Ref 08/2026"
  },
  {
    supplier: "VITÓRIA CLÍNICA MÉDICA E ODONTOLOGIA LTDA",
    invoiceNumber: "85883",
    installment: 1,
    dueDate: "2026-08-20",
    paymentDate: "2026-08-20",
    amount: 24627.48,
    amountPaid: 24627.48,
    status: "Pago",
    category: "Serviços Médicos & Honorários PJ",
    costCenterId: "1.8",
    natureType: "Custo Variável / Operacional",
    paymentMethod: "Transferência / PIX",
    bankAccount: "Itaú Unibanco (PJ)",
    description: "Serviços Médicos e Assistenciais PJ Vitória Clínica"
  }
];

function normalize(str) {
  return String(str || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
}

async function run() {
  const isDryRun = process.argv.includes('--dry-run');
  console.log(`Iniciando importação de Contas a Pagar (Taguatinga - Agosto/2026)... Mode: ${isDryRun ? 'DRY-RUN (Simulação)' : 'REAL (Gravação)'}`);

  await signInWithEmailAndPassword(auth, 'daliam@nexa.com', 'dalia123');
  console.log('Autenticado com sucesso no Firebase Auth.');

  // Buscar documentos existentes no Firestore
  const snap = await getDocs(collection(db, 'accounts_payable'));
  const existingDocs = snap.docs.map(d => ({ id: d.id, ...d.data() }));

  console.log(`Total de documentos existentes no Firestore: ${existingDocs.length}`);

  let insertedCount = 0;
  let updatedCount = 0;
  let skippedCount = 0;
  let totalNominal = 0;
  let totalPago = 0;
  let atrasadosCount = 0;
  let pagosCount = 0;

  for (let i = 0; i < taguatingaPayables.length; i++) {
    const item = taguatingaPayables[i];
    totalNominal += item.amount;
    totalPago += item.amountPaid;
    if (item.status === 'Atrasado') atrasadosCount++;
    if (item.status === 'Pago') pagosCount++;

    const normSupplier = normalize(item.supplier);
    const normInvoice = normalize(item.invoiceNumber);

    // Encontrar match por fornecedor + nota ou fornecedor + vencimento + valor
    const match = existingDocs.find(d => {
      const dUnit = normalize(d.unit || d.unitId);
      const isTag = dUnit.includes('tag') || dUnit.includes('taguatinga');
      if (!isTag && (d.unit || d.unitId)) return false;

      const dSup = normalize(d.supplier);
      const dInv = normalize(d.invoiceNumber);

      if (normInvoice && dInv && normInvoice === dInv && (dSup.includes(normSupplier.slice(0, 5)) || normSupplier.includes(dSup.slice(0, 5)))) {
        return true;
      }
      if (Math.abs(Number(d.amount || 0) - Number(item.amount || 0)) < 0.05 && d.dueDate === item.dueDate && (dSup.includes(normSupplier.slice(0, 5)) || normSupplier.includes(dSup.slice(0, 5)))) {
        return true;
      }
      return false;
    });

    if (match) {
      console.log(`[EXISTENTE #${i+1}] ${item.supplier} | Doc: ${item.invoiceNumber} | R$ ${item.amount.toFixed(2)} (ID: ${match.id})`);
      if (!isDryRun) {
        const updateData = {
          unit: 'Taguatinga',
          unitId: 'taguatinga',
          status: item.status,
          paymentDate: item.paymentDate || match.paymentDate || '',
          amountPaid: item.status === 'Pago' ? (item.amountPaid || item.amount) : (match.amountPaid || 0),
          category: item.category || match.category,
          costCenterId: item.costCenterId || match.costCenterId,
          natureType: item.natureType || match.natureType
        };
        await updateDoc(doc(db, 'accounts_payable', match.id), updateData);
        console.log(`   -> Atualizado documento ${match.id}: ${JSON.stringify(updateData)}`);
      }
      updatedCount++;
    } else {
      console.log(`[INÉDITO #${i+1}] [${item.status.toUpperCase()}] ${item.supplier} | Doc: ${item.invoiceNumber} | R$ ${item.amount.toFixed(2)} | Venc: ${item.dueDate} | Pagto: ${item.paymentDate || 'N/A'}`);
      if (!isDryRun) {
        const newDocRef = doc(collection(db, 'accounts_payable'));
        const newRecord = {
          supplier: item.supplier,
          invoiceNumber: item.invoiceNumber,
          cnpj: item.cnpj || '',
          amount: item.amount,
          amountPaid: item.amountPaid,
          dueDate: item.dueDate,
          paymentDate: item.paymentDate,
          status: item.status,
          category: item.category,
          costCenterId: item.costCenterId,
          bankAccount: item.bankAccount,
          paymentMethod: item.paymentMethod,
          natureType: item.natureType,
          description: item.description,
          unit: 'Taguatinga',
          unitId: 'taguatinga',
          installment: item.installment || 1,
          createdAt: new Date().toISOString()
        };
        await setDoc(newDocRef, newRecord);
        console.log(`   -> Inserido no Firestore com ID: ${newDocRef.id}`);
      }
      insertedCount++;
    }
  }

  console.log('\n================ RESUMO DA IMPORTAÇÃO (TAGUATINGA) ================');
  console.log(`Total de itens na lista: ${taguatingaPayables.length}`);
  console.log(`  - Atrasados (Imagem 1): ${atrasadosCount}`);
  console.log(`  - Pagos (Imagem 2): ${pagosCount}`);
  console.log(`Total Valor Nominal / Devido: R$ ${totalNominal.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`);
  console.log(`Total Valor Efetivamente Pago: R$ ${totalPago.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`);
  console.log(`Lançamentos já existentes (atualizados): ${updatedCount}`);
  console.log(`Lançamentos novos/inseridos: ${insertedCount}`);
}

run().then(() => process.exit(0)).catch(err => {
  console.error(err);
  process.exit(1);
});
