import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { getFirestore, collection, getDocs, addDoc, updateDoc, doc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || "AIzaSyBPw7Z_nhz7osMlGcdw4wAqXGFUkH27kug",
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || "nexa-index.firebaseapp.com",
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || "nexa-index",
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || "nexa-index.firebasestorage.app",
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "1089214920796",
  appId: process.env.VITE_FIREBASE_APP_ID || "1:1089214920796:web:120f3b158f599b0236ce99",
  measurementId: process.env.VITE_FIREBASE_MEASUREMENT_ID || "G-JB7DJRKXV4"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

export const julyPayablesList = [
  // --- 09/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-09',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '46424',
    amount: 68172.80,
    amountPaid: 68172.80,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 46424 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-09',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '187581',
    amount: 375.36,
    amountPaid: 375.36,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 187581 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  // VANTIVE (09/07/2026)
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116929',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116929 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116926',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116926 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115104',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115104 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115600',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115600 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '114411',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 114411 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115467',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115467 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115560',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115560 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115562',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115562 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115563',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115563 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115564',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115564 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115601',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115601 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115602',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115602 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '117260',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 117260 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '119611',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 119611 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115106',
    amount: 2354.17,
    amountPaid: 2354.17,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115106 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '117259',
    amount: 2354.17,
    amountPaid: 2354.17,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 117259 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115107',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115107 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116921',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116921 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116924',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116924 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116320',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116320 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '117712',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 117712 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116927',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116927 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116922',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116922 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116321',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116321 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '118266',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 118266 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '1190303',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 1190303 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116110',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116110 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115109',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115109 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115064',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115064 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115108',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115108 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116471',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116471 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116470',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116470 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116469',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116469 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116920',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116920 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116925',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116925 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116928',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116928 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116919',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116919 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116776',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116776 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116775',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116775 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '117431',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 117431 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '117711',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 117711 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '118263',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 118263 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '118265',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 118265 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '119302',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 119302 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '120137',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 120137 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '120138',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 120138 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '120600',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 120600 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '120602',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 120602 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '120601',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 120601 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '121249',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 121249 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '121250',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 121250 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115105',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115105 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '115110',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 115110 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VANTIVE HEALT BRASIL LTDA',
    invoiceNumber: '116468',
    amount: 2984.56,
    amountPaid: 2984.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Entrada nota fiscal 116468 - VANTIVE HEALTH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-09',
    paymentDate: '2026-07-09',
    installment: 1,
    supplier: 'WIDES TARLEY ALVES FRETE MATERIAL FORMOSA-BETIM',
    invoiceNumber: 'FRETE-0907',
    amount: 4000.00,
    amountPaid: 4000.00,
    category: 'Serviço/Utilidades',
    costCenterId: '2.1',
    description: 'Frete material Formosa-Betim',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'PIX',
    natureType: 'Custo Operacional'
  },

  // --- 10/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'ADRIAN MOURA BOLO SEMANA DA ENFERMAGEM',
    invoiceNumber: 'EVENTO-1007',
    amount: 600.00,
    amountPaid: 600.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Bolo Semana da Enfermagem',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'PIX',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'CONTMEDI & ESTRUTURAR CONTABILIDADE E FINANCAS LTD',
    invoiceNumber: '355',
    amount: 7561.04,
    amountPaid: 7561.04,
    category: 'Jurídico, Contabilidade & Taxas Regulatórias',
    costCenterId: '3.2',
    description: 'Honorários contábeis e financeiros NF 355',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'NEW TEST MANUTENCAO ELETROMECANICA LTDA',
    invoiceNumber: '414',
    amount: 8000.00,
    amountPaid: 8000.00,
    category: 'Engenharia Clínica & Manutenção de Equipamentos',
    costCenterId: '2.2',
    description: 'Manutenção eletromecânica NF 414',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '919792',
    amount: 18862.61,
    amountPaid: 18862.61,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 919792 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'FUNDO DE CAIXA',
    invoiceNumber: '25',
    amount: 972.95,
    amountPaid: 972.95,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Reembolso fundo de caixa doc 25',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'FUNDO DE CAIXA',
    invoiceNumber: '24',
    amount: 1042.18,
    amountPaid: 1042.18,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Reembolso fundo de caixa doc 24',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'FORTECARE INDUSTRIA DE PRODUTOS MEDICOS LTDA',
    invoiceNumber: '78056',
    amount: 13151.83,
    amountPaid: 13151.83,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 78056',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'HOSPITALAR COMERCIO E REPRESENTACOES LTDA',
    invoiceNumber: '12381',
    amount: 1220.92,
    amountPaid: 1248.13,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 12381 (Líquido pago: R$ 1.248,13)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '922370',
    amount: 4100.00,
    amountPaid: 4100.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 922370 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '2152515',
    amount: 2612.75,
    amountPaid: 2612.75,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 2152515 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '929349',
    amount: 1480.70,
    amountPaid: 1480.70,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 929349',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'BTT TELECOMUNICACOES S/A',
    invoiceNumber: '14437089',
    amount: 462.00,
    amountPaid: 462.00,
    category: 'TI, Telecom & Softwares de Saúde',
    costCenterId: '2.4',
    description: 'Telecomunicação NF 14437089',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'ALTERDATA TECNOLOGIA EM INFORMATICA LTDA',
    invoiceNumber: '636603',
    amount: 763.69,
    amountPaid: 763.69,
    category: 'TI, Telecom & Softwares de Saúde',
    costCenterId: '2.4',
    description: 'Software / TI NF 636603',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'VALLITECH EQUIPAMENTOS HOSPITALARES',
    invoiceNumber: '118264',
    amount: 2354.17,
    amountPaid: 2354.17,
    category: 'Equipamento',
    costCenterId: '2.2',
    description: 'Entrada nota fiscal 118264 - VALLITECH',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 4,
    supplier: 'LEVEROS',
    invoiceNumber: 'ACORDO-P4',
    amount: 7740.39,
    amountPaid: 7740.39,
    category: 'Engenharia Clínica & Manutenção de Equipamentos',
    costCenterId: '2.2',
    description: 'Acordo Climatização / Equipamentos Parc. 4',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: '4INFRA CONSULTORIA EM TI LTDA',
    invoiceNumber: '1663',
    amount: 585.00,
    amountPaid: 585.00,
    category: 'TI, Telecom & Softwares de Saúde',
    costCenterId: '2.4',
    description: 'Consultoria de TI NF 1663',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'MAXCOM SEGURANCA MAXIMA LTDA',
    invoiceNumber: '2911',
    amount: 215.79,
    amountPaid: 215.79,
    category: 'Serviço/Utilidades',
    costCenterId: '2.1',
    description: 'Segurança e Monitoramento NF 2911',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'ASKSEG ENGENHARIA E SERVIÇOS LTDA',
    invoiceNumber: '64',
    amount: 3850.00,
    amountPaid: 3850.00,
    category: 'Engenharia Clínica & Manutenção de Equipamentos',
    costCenterId: '2.2',
    description: 'Serviços de Engenharia e Segurança NF 64',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'BIOFY LABORATORIOS LTDA',
    invoiceNumber: '123',
    amount: 319.66,
    amountPaid: 319.66,
    category: 'Laboratórios & Exames Especializados',
    costCenterId: '1.4',
    description: 'Exames laboratoriais NF 123',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'BIOFY LABORATORIOS LTDA',
    invoiceNumber: '122',
    amount: 2708.71,
    amountPaid: 2708.71,
    category: 'Laboratórios & Exames Especializados',
    costCenterId: '1.4',
    description: 'Exames laboratoriais NF 122',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'MAPEL MAQUINAS E ARTIGOS DE ESCRITORIO LTDA',
    invoiceNumber: '65412',
    amount: 4077.98,
    amountPaid: 4186.45,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Artigos de escritório NF 65412 (Líquido: R$ 4.186,45)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-10',
    paymentDate: '2026-07-10',
    installment: 1,
    supplier: 'WIDES TARLEY ALVES FRETE MATERIAL FORMOSA-BETIM',
    invoiceNumber: 'FRETE-1007',
    amount: 1900.00,
    amountPaid: 1900.00,
    category: 'Serviço/Utilidades',
    costCenterId: '2.1',
    description: 'Frete material Formosa-Betim',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'PIX',
    natureType: 'Custo Operacional'
  },

  // --- 13/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-13',
    paymentDate: '2026-07-13',
    installment: 1,
    supplier: 'FGTS VERONICA KETHELLY',
    invoiceNumber: 'FGTS-VERONICA',
    amount: 1279.57,
    amountPaid: 1279.57,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Veronica Kethelly',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-13',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'TRCT VERONICA KETHELLY',
    invoiceNumber: 'TRCT-VERONICA',
    amount: 40.59,
    amountPaid: 40.59,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Veronica Kethelly',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },

  // --- 14/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS ELIANE DE PAULA',
    invoiceNumber: 'FGTS-ELIANE-1',
    amount: 156.14,
    amountPaid: 156.14,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Eliane de Paula',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS ELIANE DE PAULA',
    invoiceNumber: 'FGTS-ELIANE-2',
    amount: 38.71,
    amountPaid: 38.71,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Eliane de Paula',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS JURANDI BASTOS',
    invoiceNumber: 'FGTS-JURANDI-1',
    amount: 216.82,
    amountPaid: 216.82,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Jurandi Bastos',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS JURANDI BASTOS',
    invoiceNumber: 'FGTS-JURANDI-2',
    amount: 50.94,
    amountPaid: 50.94,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Jurandi Bastos',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS MARIA AUXILIADORA',
    invoiceNumber: 'FGTS-AUXILIADORA-1',
    amount: 165.48,
    amountPaid: 165.48,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Maria Auxiliadora',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS MARIA AUXILIADORA',
    invoiceNumber: 'FGTS-AUXILIADORA-2',
    amount: 46.72,
    amountPaid: 46.72,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Maria Auxiliadora',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS MARIA LUCIA',
    invoiceNumber: 'FGTS-LUCIA-1',
    amount: 168.47,
    amountPaid: 168.47,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Maria Lucia',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS MARIA LUCIA',
    invoiceNumber: 'FGTS-LUCIA-2',
    amount: 90.46,
    amountPaid: 90.46,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Maria Lucia',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS ROSILENE MENDES',
    invoiceNumber: 'FGTS-ROSILENE-1',
    amount: 165.46,
    amountPaid: 165.46,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Rosilene Mendes',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'FGTS ROSILENE MENDES',
    invoiceNumber: 'FGTS-ROSILENE-2',
    amount: 68.65,
    amountPaid: 68.65,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Rosilene Mendes',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'TRCT ELIANE DE PAULA',
    invoiceNumber: 'TRCT-ELIANE',
    amount: 886.32,
    amountPaid: 886.32,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Eliane de Paula',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'TRCT JURANDI BASTOS',
    invoiceNumber: 'TRCT-JURANDI',
    amount: 1378.53,
    amountPaid: 1378.53,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Jurandi Bastos',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'TRCT MARIA AUXILIADORA',
    invoiceNumber: 'TRCT-AUXILIADORA',
    amount: 999.93,
    amountPaid: 999.93,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Maria Auxiliadora',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'TRCT MARIA LUCIA',
    invoiceNumber: 'TRCT-LUCIA',
    amount: 1743.51,
    amountPaid: 1743.51,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Maria Lucia',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-14',
    paymentDate: '2026-07-14',
    installment: 1,
    supplier: 'TRCT ROSILENE MENDES',
    invoiceNumber: 'TRCT-ROSILENE',
    amount: 1232.61,
    amountPaid: 1232.61,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Rosilene Mendes',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },

  // --- 15/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-15',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'OXIMIL OXIGENIO MINAS GERAIS LTDA',
    invoiceNumber: '27961',
    amount: 310.40,
    amountPaid: 322.72,
    category: 'Gases Medicinais (Oxigênio/Ar)',
    costCenterId: '1.5',
    description: 'Gases medicinais NF 27961 (Líquido: R$ 322,72)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-15',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'N & K TECNOLOGIA LTDA',
    invoiceNumber: '12859',
    amount: 574.42,
    amountPaid: 574.42,
    category: 'TI, Telecom & Softwares de Saúde',
    costCenterId: '2.4',
    description: 'Serviços de TI / Tecnologia NF 12859',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-15',
    paymentDate: '2026-07-15',
    installment: 12,
    installmentNumber: 12,
    supplier: 'EMPRESTIMO BANCARIO SICOOB',
    invoiceNumber: 'EMP-SICOOB-P12',
    amount: 55493.38,
    amountPaid: 51198.24,
    category: 'Outros',
    costCenterId: '3.4',
    description: 'Parcela 12 Empréstimo Sicoob (Líquido debitado: R$ 51.198,24)',
    bankAccount: 'Sicoob',
    paymentMethod: 'Débito em Conta',
    natureType: 'Amortização Financeira'
  },

  // --- 16/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS LEANDRO AUGUSTO',
    invoiceNumber: 'FGTS-LEANDRO-1',
    amount: 511.72,
    amountPaid: 511.72,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Leandro Augusto',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS LEANDRO AUGUSTO',
    invoiceNumber: 'FGTS-LEANDRO-2',
    amount: 621.29,
    amountPaid: 621.29,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Leandro Augusto',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS LORRAINE CRISTINA',
    invoiceNumber: 'FGTS-LORRAINE',
    amount: 3571.20,
    amountPaid: 3571.20,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Lorraine Cristina',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS MARLENE ELIAS',
    invoiceNumber: 'FGTS-MARLENE-1',
    amount: 878.76,
    amountPaid: 878.76,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Marlene Elias',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS MARLENE ELIAS',
    invoiceNumber: 'FGTS-MARLENE-2',
    amount: 1173.77,
    amountPaid: 1173.77,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Marlene Elias',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS ROSEMARY ARANTES',
    invoiceNumber: 'FGTS-ROSEMARY-1',
    amount: 186.79,
    amountPaid: 186.79,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Rosemary Arantes',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS ROSEMARY ARANTES',
    invoiceNumber: 'FGTS-ROSEMARY-2',
    amount: 579.66,
    amountPaid: 579.66,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Rosemary Arantes',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-16',
    installment: 1,
    supplier: 'FGTS SERAFINA APARECIDA',
    invoiceNumber: 'FGTS-SERAFINA-1',
    amount: 188.82,
    amountPaid: 188.82,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Serafina Aparecida',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-16',
    installment: 1,
    supplier: 'FGTS SERAFINA APARECIDA',
    invoiceNumber: 'FGTS-SERAFINA-2',
    amount: 626.89,
    amountPaid: 626.89,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Serafina Aparecida',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS SUELLEN COSTA',
    invoiceNumber: 'FGTS-SUELLEN-1',
    amount: 968.18,
    amountPaid: 968.18,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Suellen Costa',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'FGTS SUELLEN COSTA',
    invoiceNumber: 'FGTS-SUELLEN-2',
    amount: 1078.91,
    amountPaid: 1078.91,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Suellen Costa',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'TRCT LEANDRO AUGUSTO',
    invoiceNumber: 'TRCT-LEANDRO',
    amount: 3289.12,
    amountPaid: 3289.12,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Leandro Augusto',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'TRCT LORRAINE CRISTINA',
    invoiceNumber: 'TRCT-LORRAINE',
    amount: 3749.08,
    amountPaid: 3749.08,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Lorraine Cristina',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'TRCT MARLENE ELIAS',
    invoiceNumber: 'TRCT-MARLENE',
    amount: 5024.58,
    amountPaid: 5024.58,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Marlene Elias',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'TRCT NUBIA DE OLIVEIRA',
    invoiceNumber: 'TRCT-NUBIA',
    amount: 0.00,
    amountPaid: 0.00,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Nubia de Oliveira (Zerada)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-15',
    installment: 1,
    supplier: 'TRCT ROSEMARY ARANTES',
    invoiceNumber: 'TRCT-ROSEMARY',
    amount: 2983.09,
    amountPaid: 2983.09,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Rosemary Arantes',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-16',
    installment: 1,
    supplier: 'TRCT SERAFINA APARECIDA',
    invoiceNumber: 'TRCT-SERAFINA',
    amount: 3141.77,
    amountPaid: 3141.77,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Serafina Aparecida',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-16',
    paymentDate: '2026-07-16',
    installment: 1,
    supplier: 'TRCT SUELLEN COSTA',
    invoiceNumber: 'TRCT-SUELLEN',
    amount: 4020.59,
    amountPaid: 4020.59,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Suellen Costa',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },

  // --- 17/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-17',
    paymentDate: '2026-07-17',
    installment: 1,
    supplier: 'POSTO TREVO BETIM LTDA',
    invoiceNumber: '23148',
    amount: 629.00,
    amountPaid: 629.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Combustível / Abastecimento NF 23148',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },

  // --- 18/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-18',
    paymentDate: '2026-08-04',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'INTENSIVEMED IMPORTAÇÃO E COMERCIO LTDA',
    invoiceNumber: '411575',
    amount: 4536.00,
    amountPaid: 4536.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 411575 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-18',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149652',
    amount: 1428.00,
    amountPaid: 1428.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e higiene NF 149652',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-18',
    paymentDate: '2026-08-04',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'FORTECARE INDUSTRIA DE PRODUTOS MEDICOS LTDA',
    invoiceNumber: '78056',
    amount: 12772.24,
    amountPaid: 12772.24,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 78056 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 19/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-19',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'L.F WOLF ARIAS HOSPITALARES LTDA',
    invoiceNumber: '28923',
    amount: 468.00,
    amountPaid: 468.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 28923 - L.F WOLF',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-19',
    paymentDate: '2026-08-05',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '148383',
    amount: 654.10,
    amountPaid: 654.10,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e higiene NF 148383 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-19',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'MEC Q COMERCIO E SERVICOS DE METROLOGIA INDUSTRIAL',
    invoiceNumber: '943',
    amount: 495.70,
    amountPaid: 495.70,
    category: 'Engenharia Clínica & Manutenção de Equipamentos',
    costCenterId: '2.2',
    description: 'Metrologia / Manutenção de Equipamentos NF 943',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },

  // --- 20/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'FGTS DALVA TEOFILO',
    invoiceNumber: 'FGTS-DALVA-1',
    amount: 392.23,
    amountPaid: 392.23,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Dalva Teofilo',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'FGTS DALVA TEOFILO',
    invoiceNumber: 'FGTS-DALVA-2',
    amount: 775.91,
    amountPaid: 775.91,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Dalva Teofilo',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'FGTS MARIA VILANI',
    invoiceNumber: 'FGTS-VILANI-1',
    amount: 687.56,
    amountPaid: 687.56,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Maria Vilani',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'FGTS MARIA VILANI',
    invoiceNumber: 'FGTS-VILANI-2',
    amount: 1341.70,
    amountPaid: 1341.70,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Maria Vilani',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-08-04',
    installment: '4-5',
    supplier: 'MAPEL MAQUINAS E ARTIGOS DE ESCRITORIO LTDA',
    invoiceNumber: 'ACORDO-MAPEL-4-5',
    amount: 3941.94,
    amountPaid: 4215.92,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Acordo Mapel Parc. 4-5 (Líquido: R$ 4.215,92)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'GUIA FGTS',
    invoiceNumber: 'GUIA-FGTS-072026',
    amount: 41168.11,
    amountPaid: 41168.11,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Guia Geral FGTS Competência 06/2026',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'GUIA FGTS CONSIGNADO',
    invoiceNumber: 'FGTS-CONSIGNADO-072026',
    amount: 13635.11,
    amountPaid: 13635.11,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Guia FGTS Consignado',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-08-04',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'ACACIA COMERCIO DE MEDICAMENTOS LTDA',
    invoiceNumber: '346506',
    amount: 7634.54,
    amountPaid: 7634.54,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 346506 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-08-05',
    installment: 17,
    installmentNumber: 17,
    supplier: 'EMPRESTIMO ALCEU SERVIÇOS',
    invoiceNumber: 'EMP-ALCEU-P17',
    amount: 54465.83,
    amountPaid: 56492.84,
    category: 'Outros',
    costCenterId: '3.4',
    description: 'Parcela 17 Empréstimo Alceu Serviços (Líquido: R$ 56.492,84)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Amortização Financeira'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-31',
    installment: '3-5',
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: 'ACORDO-GERAIS-3-5',
    amount: 16800.07,
    amountPaid: 16800.07,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Acordo Gerais Parc. 3-5',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'INDUSTRIA E COMERCIO NUTRIVIDA LTDA - ME',
    invoiceNumber: '7686',
    amount: 11832.60,
    amountPaid: 12163.81,
    category: 'Nutrição, Dietética & Copa de Pacientes',
    costCenterId: '2.6',
    description: 'Nutrição enteral / dietética NF 7686 (Líquido: R$ 12.163,81)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'TRINDADE BARBOSA ANALISES CLINICAS LTDA',
    invoiceNumber: '3193',
    amount: 51335.64,
    amountPaid: 51335.64,
    category: 'Laboratórios & Exames Especializados',
    costCenterId: '1.4',
    description: 'Análises clínicas e exames NF 3193',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'TRCT DALVA TEOFILO',
    invoiceNumber: 'TRCT-DALVA',
    amount: 3658.46,
    amountPaid: 3658.46,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Dalva Teofilo',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-20',
    paymentDate: '2026-07-20',
    installment: 1,
    supplier: 'TRCT MARIA VILANI',
    invoiceNumber: 'TRCT-VILANI',
    amount: 5572.89,
    amountPaid: 5572.89,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Maria Vilani',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },

  // --- 21/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-21',
    paymentDate: '2026-07-21',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '148497',
    amount: 1285.78,
    amountPaid: 1285.78,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e higiene NF 148497 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-21',
    paymentDate: '2026-07-21',
    installment: 1,
    supplier: 'OXIMIL OXIGENIO MINAS GERAIS LTDA',
    invoiceNumber: '288304',
    amount: 383.77,
    amountPaid: 401.61,
    category: 'Gases Medicinais (Oxigênio/Ar)',
    costCenterId: '1.5',
    description: 'Gases medicinais NF 288304 (Líquido: R$ 401,61)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 22/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-07-22',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5980',
    amount: 5960.00,
    amountPaid: 5960.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5980 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-07-22',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5979',
    amount: 19586.00,
    amountPaid: 19586.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5979 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-07-22',
    installment: 1,
    supplier: 'BHFIOS PRODUTOS MÉDICOS LTDA',
    invoiceNumber: '2889',
    amount: 3168.00,
    amountPaid: 3168.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 2889 - BHFIOS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-07-22',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '47116',
    amount: 35003.00,
    amountPaid: 35003.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 47116 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 23/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'FGTS IANKA LORRANY',
    invoiceNumber: 'FGTS-IANKA',
    amount: 327.14,
    amountPaid: 327.14,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Ianka Lorrany',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'FGTS MIGUEL MONTEIRO',
    invoiceNumber: 'FGTS-MIGUEL',
    amount: 116.14,
    amountPaid: 116.14,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Miguel Monteiro',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'INSTITUTO RAMACRISNA',
    invoiceNumber: '1440',
    amount: 1770.00,
    amountPaid: 1770.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Jovem Aprendiz / Capacitação NF 1440',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930653',
    amount: 1146.11,
    amountPaid: 1146.11,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930653',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930077',
    amount: 1907.22,
    amountPaid: 1907.22,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930077',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'INTENSIVEMED IMPORTAÇÃO E COMERCIO LTDA',
    invoiceNumber: '413464',
    amount: 5280.00,
    amountPaid: 5280.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 413464 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149812',
    amount: 2460.00,
    amountPaid: 2460.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e higiene NF 149812',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930643',
    amount: 787.50,
    amountPaid: 787.50,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930643',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930644',
    amount: 830.32,
    amountPaid: 830.32,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930644',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  }
];

async function runAuditAndImport(isDryRun = true) {
  console.log(`=== AUDITORIA E IMPORTAÇÃO DE CONTAS A PAGAR (BETIM - JULHO 2026) [DryRun: ${isDryRun}] ===\n`);
  await signInWithEmailAndPassword(auth, 'daliam@nexa.com', 'dalia123');
  console.log('✓ Autenticado com sucesso no Firebase.');

  const colRef = collection(db, 'accounts_payable');
  const snap = await getDocs(colRef);
  const existingPayables = snap.docs.map(d => ({ id: d.id, ...d.data() }));

  console.log(`Total de lançamentos existentes no Firestore: ${existingPayables.length}`);

  let insertedCount = 0;
  let alreadyExistsCount = 0;
  let updatedCount = 0;
  let totalNominalAmount = 0;
  let totalPaidAmount = 0;

  for (const [idx, item] of julyPayablesList.entries()) {
    totalNominalAmount += item.amount;
    totalPaidAmount += item.amountPaid;

    // Search for match in DB
    const match = existingPayables.find(p => {
      const sameSupplier = String(p.supplier || '').trim().toLowerCase() === item.supplier.trim().toLowerCase();
      const sameInvoice = String(p.invoiceNumber || '').trim().toLowerCase() === item.invoiceNumber.trim().toLowerCase();
      const sameAmount = Math.abs((Number(p.amount) || 0) - item.amount) < 0.05 || Math.abs((Number(p.amountPaid) || 0) - item.amountPaid) < 0.05;
      const sameDueDate = String(p.dueDate || '').trim() === item.dueDate;
      
      // Match criteria
      if (sameInvoice && item.invoiceNumber !== '' && !item.invoiceNumber.startsWith('SEM') && !item.invoiceNumber.startsWith('EVENTO')) {
        return (sameSupplier || sameAmount);
      }
      return sameSupplier && sameAmount && sameDueDate;
    });

    if (match) {
      alreadyExistsCount++;
      console.log(`[EXISTENTE #${idx + 1}] ${item.supplier} | Doc: ${item.invoiceNumber} | R$ ${item.amount.toFixed(2)} (ID: ${match.id})`);
      if (!isDryRun) {
        // Ensure status is 'Pago' and has unit Betim
        const updates = {};
        if (match.status !== 'Pago') updates.status = 'Pago';
        if (match.unit !== 'Betim') updates.unit = 'Betim';
        if (match.unitId !== 'betim') updates.unitId = 'betim';
        if (!match.paymentDate && item.paymentDate) updates.paymentDate = item.paymentDate;
        if (!match.amountPaid && item.amountPaid) updates.amountPaid = item.amountPaid;

        if (Object.keys(updates).length > 0) {
          await updateDoc(doc(db, 'accounts_payable', match.id), updates);
          console.log(`   -> Atualizado documento ${match.id}: ${JSON.stringify(updates)}`);
          updatedCount++;
        }
      }
    } else {
      insertedCount++;
      console.log(`[INÉDITO #${idx + 1}] ${item.supplier} | Doc: ${item.invoiceNumber} | R$ ${item.amount.toFixed(2)} | Venc: ${item.dueDate} | Pagto: ${item.paymentDate}`);
      if (!isDryRun) {
        const payload = {
          ...item,
          unit: 'Betim',
          unitId: 'betim',
          cnpj: item.cnpj || '00.000.000/0001-00',
          createdAt: new Date().toISOString()
        };
        const ref = await addDoc(colRef, payload);
        console.log(`   -> Inserido no Firestore com ID: ${ref.id}`);
      }
    }
  }

  console.log('\n================ RESUMO ================');
  console.log(`Total de itens na lista: ${julyPayablesList.length}`);
  console.log(`Total Valor Nominal: R$ ${totalNominalAmount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`);
  console.log(`Total Valor Pago: R$ ${totalPaidAmount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`);
  console.log(`Lançamentos já existentes: ${alreadyExistsCount}`);
  console.log(`Lançamentos novos/inseridos: ${insertedCount}`);
  console.log(`Lançamentos atualizados: ${updatedCount}`);
}

const isDry = process.argv.includes('--dry-run');
runAuditAndImport(isDry).then(() => process.exit(0)).catch(err => {
  console.error(err);
  process.exit(1);
});
