import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { getFirestore, collection, getDocs, addDoc, updateDoc, doc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: process.env.VITE_FIREBASE_API_KEY || "AIzaSyBPw7Z_nhz7osMlGcdw4wAqXGFUkH27kug",
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || "nexa-index.firebaseapp.com",
  projectId: process.env.VITE_FIREBASE_PROJECT_ID || "nexa-index",
  storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || "nexa-index.firebasestorage.app",
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "1089214920796",
  appId: process.env.VITE_FIREBASE_APP_ID || "1:1089214920796:web:120f3b158f599b0236ce99",
  measurementId: process.env.VITE_FIREBASE_MEASUREMENT_ID || "G-JB7DJRKXV4"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

export const julyPart2PayablesList = [
  // --- Atualizações de datas de liquidação do dia 21/07 a 23/07 ---
  {
    status: 'Pago',
    dueDate: '2026-07-21',
    paymentDate: '2026-08-05',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '148497',
    amount: 1285.78,
    amountPaid: 1285.78,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e higiene NF 148497 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-21',
    paymentDate: '2026-07-29',
    installment: 1,
    supplier: 'OXIMIL OXIGENIO MINAS GERAIS LTDA',
    invoiceNumber: '288304',
    amount: 383.77,
    amountPaid: 401.61,
    category: 'Gases Medicinais (Oxigênio/Ar)',
    costCenterId: '1.5',
    description: 'Gases medicinais NF 288304 (Líquido: R$ 401,61)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-07-22',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5980',
    amount: 5960.00,
    amountPaid: 5960.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5980 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5979',
    amount: 19586.00,
    amountPaid: 19586.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5979 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-08-06',
    installment: 1,
    supplier: 'BHFIOS PRODUTOS MÉDICOS LTDA',
    invoiceNumber: '2889',
    amount: 3168.00,
    amountPaid: 3168.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 2889 - BHFIOS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-22',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '47116',
    amount: 35003.00,
    amountPaid: 35003.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 47116 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'FGTS IANKA LORRANY',
    invoiceNumber: 'FGTS-IANKA',
    amount: 327.14,
    amountPaid: 327.14,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Ianka Lorrany',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'FGTS MIGUEL MONTEIRO',
    invoiceNumber: 'FGTS-MIGUEL',
    amount: 116.14,
    amountPaid: 116.14,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Encargo FGTS - Miguel Monteiro',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'INSTITUTO RAMACRISNA',
    invoiceNumber: '1440',
    amount: 1770.00,
    amountPaid: 1770.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Jovem Aprendiz / Capacitação NF 1440',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930653',
    amount: 1146.11,
    amountPaid: 1146.11,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930653',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930077',
    amount: 1907.22,
    amountPaid: 1907.22,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930077',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-08-04',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'INTENSIVEMED IMPORTAÇÃO E COMERCIO LTDA',
    invoiceNumber: '413464',
    amount: 5280.00,
    amountPaid: 5280.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 413464 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149812',
    amount: 2460.00,
    amountPaid: 2460.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e higiene NF 149812',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930643',
    amount: 787.50,
    amountPaid: 787.50,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930643',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '930644',
    amount: 830.32,
    amountPaid: 830.32,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 930644',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- Novos Lançamentos de 23/07/2026 em diante ---
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: '2/3',
    supplier: 'TRCT FILIPE HENRIQUE JUDICIAL',
    invoiceNumber: 'TRCT-FILIPE-JUD',
    amount: 6000.00,
    amountPaid: 6000.00,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Acordo Judicial Trabalhista TRCT - Filipe Henrique (Parc. 2/3)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'TRCT IANKA LORRANY',
    invoiceNumber: 'TRCT-IANKA',
    amount: 2492.11,
    amountPaid: 2492.11,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Ianka Lorrany',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-23',
    paymentDate: '2026-07-23',
    installment: 1,
    supplier: 'TRCT MIGUEL MONTEIRO',
    invoiceNumber: 'TRCT-MIGUEL',
    amount: 2069.43,
    amountPaid: 2069.43,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Rescisão TRCT - Miguel Monteiro',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo com Pessoal'
  },

  // --- 24/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-24',
    paymentDate: '2026-08-04',
    installment: 2,
    installmentNumber: 2,
    installmentCount: 2,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '927240',
    amount: 24013.67,
    amountPaid: 24013.67,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 927240 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-24',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149843',
    amount: 750.00,
    amountPaid: 750.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e alimentos NF 149843',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-24',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149857',
    amount: 2820.00,
    amountPaid: 2820.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e alimentos NF 149857',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-24',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149837',
    amount: 90.00,
    amountPaid: 90.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e alimentos NF 149837',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-24',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'PANAMERICANA DISTRIBUIDORA LTDA',
    invoiceNumber: '211202',
    amount: 387.24,
    amountPaid: 387.24,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos / Distribuidora NF 211202',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-24',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'PANAMERICANA DISTRIBUIDORA LTDA',
    invoiceNumber: '211210',
    amount: 2329.20,
    amountPaid: 2329.20,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos / Distribuidora NF 211210',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 25/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'AMBIENTEC SOLUÇÕES EM RESÍDUOS',
    invoiceNumber: '23013',
    amount: 14702.88,
    amountPaid: 14702.88,
    category: 'Gestão de Resíduos de Saúde (Lixo Infectante/RSS)',
    costCenterId: '2.3',
    description: 'Coleta e tratamento de resíduos infectantes NF 23013',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '14978',
    amount: 264.00,
    amountPaid: 264.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e alimentos NF 14978',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'PJ PABLO TECH COSTA',
    invoiceNumber: '43',
    amount: 4000.00,
    amountPaid: 4000.00,
    category: 'TI, Telecom & Softwares de Saúde',
    costCenterId: '2.4',
    description: 'Serviços de Tecnologia / TI PJ NF 43',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'INTENSIVEMED IMPORTAÇÃO E COMERCIO LTDA',
    invoiceNumber: '415586',
    amount: 6837.00,
    amountPaid: 6837.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 415586 - INTENSIVEMED',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'PJ DALIA',
    invoiceNumber: 'PJ-DALIA-072026',
    amount: 35000.00,
    amountPaid: 35000.00,
    category: 'Serviços Médicos & Honorários PJ',
    costCenterId: '1.8',
    description: 'Honorários Médicos PJ - Dra. Dalia',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'PJ JANAINA SOARES',
    invoiceNumber: '7',
    amount: 9000.00,
    amountPaid: 9000.00,
    category: 'Serviços Médicos & Honorários PJ',
    costCenterId: '1.8',
    description: 'Honorários Médicos PJ - Dra. Janaina Soares NF 7',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'PJ WAGNER',
    invoiceNumber: '9',
    amount: 7000.00,
    amountPaid: 7000.00,
    category: 'Serviços Médicos & Honorários PJ',
    costCenterId: '1.8',
    description: 'Honorários Médicos PJ - Dr. Wagner NF 9',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'PJ MATEUS',
    invoiceNumber: '6',
    amount: 4000.00,
    amountPaid: 4000.00,
    category: 'Serviços Médicos & Honorários PJ',
    costCenterId: '1.8',
    description: 'Honorários Médicos PJ - Dr. Mateus NF 6',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'PJ HAMILTON',
    invoiceNumber: '2',
    amount: 16000.00,
    amountPaid: 16000.00,
    category: 'Serviços Médicos & Honorários PJ',
    costCenterId: '1.8',
    description: 'Honorários Médicos PJ - Dr. Hamilton NF 2',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-25',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'PRODUÇÃO MEDICA PJ',
    invoiceNumber: 'PROD-MED-072026',
    amount: 323707.43,
    amountPaid: 323707.43,
    category: 'Serviços Médicos & Honorários PJ',
    costCenterId: '1.8',
    description: 'Produção Médica Corpo Clínico PJ Julho/2026',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'PIX',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 26/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'LABORATORIOS B.BRAUN S.A.',
    invoiceNumber: '1084185',
    amount: 11385.00,
    amountPaid: 11715.31,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos B.Braun NF 1084185 (Líquido: R$ 11.715,31)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'LABORATORIOS B.BRAUN S.A.',
    invoiceNumber: '1084494',
    amount: 28770.00,
    amountPaid: 29575.56,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos B.Braun NF 1084494 (Líquido: R$ 29.575,56)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 2,
    supplier: 'LEANDRO DE ASSIS ALMEIDA COSTA',
    invoiceNumber: '6',
    amount: 3900.00,
    amountPaid: 3900.00,
    category: 'Serviços Médicos & Honorários PJ',
    costCenterId: '1.8',
    description: 'Prestação de Serviços Médicos / Honorários NF 6',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-06',
    installment: 1,
    supplier: 'BHFIOS PRODUTOS MÉDICOS LTDA',
    invoiceNumber: '2875',
    amount: 1680.00,
    amountPaid: 1680.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos médicos NF 2875 - BHFIOS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '252771',
    amount: 2850.00,
    amountPaid: 2850.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 252771',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '253202',
    amount: 10020.25,
    amountPaid: 10020.25,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 253202',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'ACACIA COMERCIO DE MEDICAMENTOS LTDA',
    invoiceNumber: '346655',
    amount: 2690.00,
    amountPaid: 2690.00,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 346655',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5965',
    amount: 19586.00,
    amountPaid: 19586.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5965 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'INTENSIVEMED IMPORTAÇÃO E COMERCIO LTDA',
    invoiceNumber: '413464',
    amount: 5280.00,
    amountPaid: 5280.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 413464 (Parc. 1)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '927388',
    amount: 2730.00,
    amountPaid: 2730.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 927388',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '2165870',
    amount: 1858.30,
    amountPaid: 1858.30,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 2165870',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: '927240',
    amount: 24013.67,
    amountPaid: 24013.67,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 927240 (Parc. 1)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 2,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '147957',
    amount: 594.00,
    amountPaid: 594.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza NF 147957 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 2,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '147896',
    amount: 3106.36,
    amountPaid: 3106.36,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza NF 147896 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 2,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '147850',
    amount: 308.70,
    amountPaid: 308.70,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza NF 147850 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 2,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '147828',
    amount: 1501.68,
    amountPaid: 1501.68,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza NF 147828 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 2,
    supplier: 'SHFBRASIL.COM LTDA',
    invoiceNumber: '851',
    amount: 9264.00,
    amountPaid: 9264.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos e materiais NF 851 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 2,
    supplier: 'ACACIA COMERCIO DE MEDICAMENTOS LTDA',
    invoiceNumber: '344686',
    amount: 7625.50,
    amountPaid: 7625.50,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 344686 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149032',
    amount: 351.80,
    amountPaid: 351.80,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza NF 149032',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 4,
    supplier: 'INTENSIVEMED IMPORTAÇÃO E COMERCIO LTDA ACORDO',
    invoiceNumber: 'ACORDO-INTENSIVE-P4',
    amount: 20277.63,
    amountPaid: 20277.63,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Acordo Fornecedor Intensivemed (Parc. 4)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '46940',
    amount: 68172.80,
    amountPaid: 68172.80,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos dialíticos NF 46940 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'ACACIA COMERCIO DE MEDICAMENTOS LTDA',
    invoiceNumber: '346506',
    amount: 7634.54,
    amountPaid: 7634.54,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 346506 (Parc. 1)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5964',
    amount: 19586.00,
    amountPaid: 19586.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5964 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149098',
    amount: 6768.53,
    amountPaid: 6768.53,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza e copa NF 149098',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'ACACIA COMERCIO DE MEDICAMENTOS LTDA',
    invoiceNumber: '346768',
    amount: 28015.01,
    amountPaid: 28015.01,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 346768',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'LABORATORIOS B.BRAUN S.A.',
    invoiceNumber: '1087365',
    amount: 8628.24,
    amountPaid: 8815.49,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos B.Braun NF 1087365 (Líquido: R$ 8.815,49)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'L.F WOLF ARIAS HOSPITALARES LTDA',
    invoiceNumber: '28895',
    amount: 3394.00,
    amountPaid: 3394.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos hospitalares NF 28895 - L.F WOLF',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '188587',
    amount: 13750.00,
    amountPaid: 13750.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos dialíticos NF 188587 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5976',
    amount: 19586.00,
    amountPaid: 19586.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5976 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'LABORATORIOS B.BRAUN S.A.',
    invoiceNumber: '1086478',
    amount: 5580.61,
    amountPaid: 5692.21,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos B.Braun NF 1086478 (Líquido: R$ 5.692,21)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'ACACIA COMERCIO DE MEDICAMENTOS LTDA',
    invoiceNumber: '347229',
    amount: 8193.15,
    amountPaid: 8193.15,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 347229',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 2,
    supplier: 'ACACIA COMERCIO DE MEDICAMENTOS LTDA',
    invoiceNumber: '345685',
    amount: 7580.07,
    amountPaid: 7580.07,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 345685 (Parc. 2)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'COMERCIAL DA MATA LIMPEZA E ALIMENTOS LTDA',
    invoiceNumber: '149371',
    amount: 1428.00,
    amountPaid: 1428.00,
    category: 'Lavanderia & Higienização Hospitalar',
    costCenterId: '2.5',
    description: 'Material de limpeza NF 149371',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'GERAIS COM. E IMP. DE MAT. E EQUIP. MEDICOS LTDA',
    invoiceNumber: '5972',
    amount: 8835.20,
    amountPaid: 8835.20,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Entrada nota fiscal 5972 - GERAIS',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-26',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'MAPEL MAQUINAS E ARTIGOS DE ESCRITORIO LTDA',
    invoiceNumber: '65554',
    amount: 3884.21,
    amountPaid: 4077.27,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Artigos de escritório NF 65554 (Líquido: R$ 4.077,27)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },

  // --- 27/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-27',
    paymentDate: '2026-07-27',
    installment: 1,
    supplier: 'OXIMIL OXIGENIO MINAS GERAIS LTDA',
    invoiceNumber: '28068',
    amount: 310.40,
    amountPaid: 316.60,
    category: 'Gases Medicinais (Oxigênio/Ar)',
    costCenterId: '1.5',
    description: 'Gases medicinais NF 28068 (Líquido: R$ 316,60)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-27',
    paymentDate: '2026-07-27',
    installment: 1,
    supplier: 'OXIMIL OXIGENIO MINAS GERAIS LTDA',
    invoiceNumber: '82354',
    amount: 317.82,
    amountPaid: 317.82,
    category: 'Gases Medicinais (Oxigênio/Ar)',
    costCenterId: '1.5',
    description: 'Gases medicinais NF 82354',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 28/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '47337',
    amount: 35003.00,
    amountPaid: 35003.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos dialíticos NF 47337 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-07-28',
    installment: 1,
    supplier: 'LABORATORIOS B.BRAUN S.A.',
    invoiceNumber: '1088671',
    amount: 24000.00,
    amountPaid: 24216.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos B.Braun NF 1088671 (Líquido: R$ 24.216,00)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-07-28',
    installment: 1,
    supplier: 'LABORATORIOS B.BRAUN S.A.',
    invoiceNumber: '1089228',
    amount: 2390.40,
    amountPaid: 2404.74,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos B.Braun NF 1089228 (Líquido: R$ 2.404,74)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-07-28',
    installment: 2,
    supplier: 'LABORATORIOS B.BRAUN S.A.',
    invoiceNumber: '176143',
    amount: 1500.00,
    amountPaid: 1506.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos B.Braun NF 176143 (Parc. 2 - Líquido: R$ 1.506,00)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-07-28',
    installment: 1,
    supplier: 'NIPRO MEDICAL',
    invoiceNumber: '46525',
    amount: 68172.80,
    amountPaid: 68172.80,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos dialíticos NF 46525 - NIPRO MEDICAL',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-07-28',
    installment: 1,
    supplier: 'MINAS WIPE NEGOCIOS LTDA',
    invoiceNumber: '134318',
    amount: 2522.15,
    amountPaid: 2641.27,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos / Compressa estéril NF 134318 Parc. 1 (Líquido: R$ 2.641,27)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-07-28',
    installment: 2,
    supplier: 'MINAS WIPE NEGOCIOS LTDA',
    invoiceNumber: '134318',
    amount: 2522.15,
    amountPaid: 2580.67,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos / Compressa estéril NF 134318 Parc. 2 (Líquido: R$ 2.580,67)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'PANAMERICANA DISTRIBUIDORA LTDA',
    invoiceNumber: '211307',
    amount: 652.00,
    amountPaid: 652.00,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 211307',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-28',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'PANAMERICANA DISTRIBUIDORA LTDA',
    invoiceNumber: '211345',
    amount: 2434.00,
    amountPaid: 2434.00,
    category: 'Medicamentos & Farmácia Clínica',
    costCenterId: '1.2',
    description: 'Medicamentos NF 211345',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 29/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-29',
    paymentDate: '2026-07-08',
    installment: 1,
    supplier: 'HOSTGATOR BRASIL LTDA',
    invoiceNumber: '7',
    amount: 845.00,
    amountPaid: 845.00,
    category: 'TI, Telecom & Softwares de Saúde',
    costCenterId: '2.4',
    description: 'Hospedagem e Servidor NF 7',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto / Cartão',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-29',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'ZOOP TECNOLOGIA - IFOOD',
    invoiceNumber: '9192',
    amount: 6800.00,
    amountPaid: 6800.00,
    category: 'Nutrição, Dietética & Copa de Pacientes',
    costCenterId: '2.6',
    description: 'Alimentação de Pacientes e Colaboradores / iFood Benefícios NF 9192',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-29',
    paymentDate: '2026-07-29',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: 'A VISTA-2907',
    amount: 16615.60,
    amountPaid: 16615.60,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Compra de Insumos Cirúrgica Rioclarense à Vista',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-29',
    paymentDate: '2026-07-29',
    installment: 1,
    supplier: 'COLETIVOS SANTA EDWIGES BETIM LTDA',
    invoiceNumber: '2037',
    amount: 8128.50,
    amountPaid: 8128.50,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Vale Transporte / Recarga Coletivos Santa Edwiges NF 2037',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo com Pessoal'
  },

  // --- 30/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-07-30',
    installment: 1,
    supplier: 'TORNEIRA PARA CAFETERIA',
    invoiceNumber: 'COMPRA-3007',
    amount: 169.00,
    amountPaid: 169.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Torneira para cafeteria / Copa',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'PIX / Débito',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-07-30',
    installment: 1,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA',
    invoiceNumber: 'A VISTA-3007',
    amount: 2778.00,
    amountPaid: 2778.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos Cirúrgica Rioclarense à Vista',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'PIX',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'D RANGEL OVIDIO CONSTANCIA MUSIC',
    invoiceNumber: '47',
    amount: 1000.00,
    amountPaid: 1000.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Serviços de Som / Ambiente NF 47',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'MINAS WIPE NEGOCIOS LTDA',
    invoiceNumber: '134946',
    amount: 943.40,
    amountPaid: 943.40,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos e compressas NF 134946',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-08-04',
    installment: '3-6',
    supplier: 'LACERDA ALIMENTAÇÃO ACORDO',
    invoiceNumber: 'ACORDO-LACERDA-3-6',
    amount: 25164.10,
    amountPaid: 25164.10,
    category: 'Nutrição, Dietética & Copa de Pacientes',
    costCenterId: '2.6',
    description: 'Acordo Fornecimento de Refeições / Dietas Lacerda (Parc. 3-6)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-08-04',
    installment: '4-9',
    supplier: 'MINAS WIPE NEGOCIOS LTDA ACORDO',
    invoiceNumber: 'ACORDO-MINASWIPE-4-9',
    amount: 1965.97,
    amountPaid: 2024.88,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Acordo Minas Wipe Parc. 4-9 (Líquido: R$ 2.024,88)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-08-04',
    installment: 5,
    supplier: 'COMERCIAL CIRURGICA RIOCLARENSE LTDA ACORDO',
    invoiceNumber: 'ACORDO-RIOCLARENSE-P5',
    amount: 55113.94,
    amountPaid: 55113.94,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Acordo Cirúrgica Rioclarense Parc. 5',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-30',
    paymentDate: '2026-07-31',
    installment: '5-10',
    supplier: 'VANTIVE HEALT BRASIL LTDA ACORDO',
    invoiceNumber: 'ACORDO-VANTIVE-5-10',
    amount: 239690.80,
    amountPaid: 239690.80,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.9',
    description: 'Acordo Diálise Peritoneal Vantive Health Parc. 5-10',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },

  // --- 31/07/2026 ---
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'L.F WOLF ARIAS HOSPITALARES LTDA',
    invoiceNumber: '28845',
    amount: 2464.00,
    amountPaid: 2464.00,
    category: 'Material Médico-Hospitalar (MatMed)',
    costCenterId: '1.1',
    description: 'Insumos hospitalares NF 28845 - L.F WOLF',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'NEW TEST MANUTENCAO ELETROMECANICA LTDA',
    invoiceNumber: '434',
    amount: 8000.00,
    amountPaid: 8000.00,
    category: 'Engenharia Clínica & Manutenção de Equipamentos',
    costCenterId: '2.2',
    description: 'Manutenção eletromecânica NF 434',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'REEMBOLSO DALIA VIAGEM 17 a 21/06',
    invoiceNumber: 'REEMBOLSO-DALIA-1721',
    amount: 3193.80,
    amountPaid: 3193.80,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Reembolso despesas de viagem Dra. Dalia (17 a 21/06)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'REEMBOLSO DALIA VIAGEM 25/06 A 01/07',
    invoiceNumber: 'REEMBOLSO-DALIA-2501',
    amount: 2226.00,
    amountPaid: 2226.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Reembolso despesas de viagem Dra. Dalia (25/06 a 01/07)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'REEMBOLSO DALIA VIAGEM REUNIÃO SES 05 A 06/06',
    invoiceNumber: 'REEMBOLSO-DALIA-SES',
    amount: 2435.00,
    amountPaid: 2435.00,
    category: 'Despesas Gerais & Administrativas',
    costCenterId: '3.3',
    description: 'Reembolso viagem reunião SES Dra. Dalia (05 a 06/06)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Transferência / PIX',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'OXIMIL OXIGENIO MINAS GERAIS LTDA',
    invoiceNumber: '19867',
    amount: 310.40,
    amountPaid: 317.97,
    category: 'Gases Medicinais (Oxigênio/Ar)',
    costCenterId: '1.5',
    description: 'Gases medicinais NF 19867 (Líquido: R$ 317,97)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Variável / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 1,
    supplier: 'ZOOP TECNOLOGIA - IFOOD',
    invoiceNumber: '9147',
    amount: 700.00,
    amountPaid: 700.00,
    category: 'Nutrição, Dietética & Copa de Pacientes',
    costCenterId: '2.6',
    description: 'iFood Refeição / Benefício NF 9147',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-08-05',
    installment: 5,
    supplier: 'CONSELHO REGIONAL DE MEDICINA-MG',
    invoiceNumber: '46810',
    amount: 985.60,
    amountPaid: 985.60,
    category: 'Jurídico, Contabilidade & Taxas Regulatórias',
    costCenterId: '3.2',
    description: 'Anuidade / Taxa CRM-MG Parc. 5',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-08-05',
    installment: 1,
    supplier: 'SINDEESS - SINDICATO DOS TRABALHADORES',
    invoiceNumber: '3424',
    amount: 2500.00,
    amountPaid: 2500.00,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Contribuição Sindical / Encargos SINDEESS NF 3424',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Boleto',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-08-04',
    installment: 1,
    supplier: 'CONSELHO FEDERAL DE FARMACIA',
    invoiceNumber: '4701007',
    amount: 779.45,
    amountPaid: 785.74,
    category: 'Jurídico, Contabilidade & Taxas Regulatórias',
    costCenterId: '3.2',
    description: 'Taxa / Anuidade Conselho Federal de Farmácia (Líquido: R$ 785,74)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Boleto Bancário',
    natureType: 'Custo Fixo / Operacional'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 8,
    supplier: 'PARCELAMENTO INSS',
    invoiceNumber: '2516',
    amount: 35493.65,
    amountPaid: 35493.65,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Guia Parcelamento INSS Débito 2516 (Parc. 8)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Débito',
    natureType: 'Custo com Pessoal'
  },
  {
    status: 'Pago',
    dueDate: '2026-07-31',
    paymentDate: '2026-07-31',
    installment: 8,
    supplier: 'PARCELAMENTO INSS',
    invoiceNumber: '2535',
    amount: 6783.51,
    amountPaid: 6783.51,
    category: 'Folha de Pagamento & Encargos Sociais',
    costCenterId: '3.1',
    description: 'Guia Parcelamento INSS Débito 2535 (Parc. 8)',
    bankAccount: 'Itaú Unibanco (PJ)',
    paymentMethod: 'Guia / Débito',
    natureType: 'Custo com Pessoal'
  }
];

async function runPart2AuditAndImport(isDryRun = true) {
  console.log(`=== AUDITORIA E IMPORTAÇÃO DE CONTAS A PAGAR PARTE 2 (BETIM - JULHO 2026) [DryRun: ${isDryRun}] ===\n`);
  await signInWithEmailAndPassword(auth, 'daliam@nexa.com', 'dalia123');
  console.log('✓ Autenticado com sucesso no Firebase.');

  const colRef = collection(db, 'accounts_payable');
  const snap = await getDocs(colRef);
  const existingPayables = snap.docs.map(d => ({ id: d.id, ...d.data() }));

  console.log(`Total de lançamentos existentes no Firestore: ${existingPayables.length}`);

  let insertedCount = 0;
  let alreadyExistsCount = 0;
  let updatedCount = 0;
  let totalNominalAmount = 0;
  let totalPaidAmount = 0;

  for (const [idx, item] of julyPart2PayablesList.entries()) {
    totalNominalAmount += item.amount;
    totalPaidAmount += item.amountPaid;

    // Search for match in DB
    const match = existingPayables.find(p => {
      const sameSupplier = String(p.supplier || '').trim().toLowerCase() === item.supplier.trim().toLowerCase();
      const sameInvoice = String(p.invoiceNumber || '').trim().toLowerCase() === item.invoiceNumber.trim().toLowerCase();
      const sameAmount = Math.abs((Number(p.amount) || 0) - item.amount) < 0.05 || Math.abs((Number(p.amountPaid) || 0) - item.amountPaid) < 0.05;
      const sameDueDate = String(p.dueDate || '').trim() === item.dueDate;
      
      // Match criteria
      if (sameInvoice && item.invoiceNumber !== '' && !item.invoiceNumber.startsWith('SEM') && !item.invoiceNumber.startsWith('COMPRA') && !item.invoiceNumber.startsWith('A VISTA')) {
        return (sameSupplier || sameAmount);
      }
      return sameSupplier && sameAmount && sameDueDate;
    });

    if (match) {
      alreadyExistsCount++;
      console.log(`[EXISTENTE #${idx + 1}] ${item.supplier} | Doc: ${item.invoiceNumber} | R$ ${item.amount.toFixed(2)} (ID: ${match.id})`);
      if (!isDryRun) {
        const updates = {};
        if (match.status !== 'Pago') updates.status = 'Pago';
        if (match.unit !== 'Betim') updates.unit = 'Betim';
        if (match.unitId !== 'betim') updates.unitId = 'betim';
        if (item.paymentDate && match.paymentDate !== item.paymentDate) updates.paymentDate = item.paymentDate;
        if (item.amountPaid && match.amountPaid !== item.amountPaid) updates.amountPaid = item.amountPaid;

        if (Object.keys(updates).length > 0) {
          await updateDoc(doc(db, 'accounts_payable', match.id), updates);
          console.log(`   -> Atualizado documento ${match.id}: ${JSON.stringify(updates)}`);
          updatedCount++;
        }
      }
    } else {
      insertedCount++;
      console.log(`[INÉDITO #${idx + 1}] ${item.supplier} | Doc: ${item.invoiceNumber} | R$ ${item.amount.toFixed(2)} | Venc: ${item.dueDate} | Pagto: ${item.paymentDate}`);
      if (!isDryRun) {
        const payload = {
          ...item,
          unit: 'Betim',
          unitId: 'betim',
          cnpj: item.cnpj || '00.000.000/0001-00',
          createdAt: new Date().toISOString()
        };
        const ref = await addDoc(colRef, payload);
        console.log(`   -> Inserido no Firestore com ID: ${ref.id}`);
      }
    }
  }

  console.log('\n================ RESUMO ================');
  console.log(`Total de itens na lista Parte 2: ${julyPart2PayablesList.length}`);
  console.log(`Total Valor Nominal: R$ ${totalNominalAmount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`);
  console.log(`Total Valor Pago: R$ ${totalPaidAmount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`);
  console.log(`Lançamentos já existentes: ${alreadyExistsCount}`);
  console.log(`Lançamentos novos/inseridos: ${insertedCount}`);
  console.log(`Lançamentos atualizados: ${updatedCount}`);
}

const isDry = process.argv.includes('--dry-run');
runPart2AuditAndImport(isDry).then(() => process.exit(0)).catch(err => {
  console.error(err);
  process.exit(1);
});
